FROM ubuntu:15.10
ENV PATH /usr/games:$PATH
ADD . /usr/local/share/quine-relay
WORKDIR /usr/local/share/quine-relay
RUN apt-get update && apt-get upgrade -y
RUN apt-get -qq install -y afnix && apt-get clean
RUN apt-get -qq install -y algol68g && apt-get clean
RUN apt-get -qq install -y aplus-fsf && apt-get clean
RUN apt-get -qq install -y asymptote && apt-get clean
RUN apt-get -qq install -y ats-lang-anairiats && apt-get clean
RUN apt-get -qq install -y bash && apt-get clean
RUN apt-get -qq install -y bc && apt-get clean
RUN apt-get -qq install -y bf && apt-get clean
RUN apt-get -qq install -y bsdgames && apt-get clean
RUN apt-get -qq install -y cduce && apt-get clean
RUN apt-get -qq install -y clisp && apt-get clean
RUN apt-get -qq install -y clojure1.6 && apt-get clean
RUN apt-get -qq install -y cmake && apt-get clean
RUN apt-get -qq install -y coffeescript && apt-get clean
RUN apt-get -qq install -y dc && apt-get clean
RUN apt-get -qq install -y ecere-dev && apt-get clean
RUN apt-get -qq install -y elixir && apt-get clean
RUN apt-get -qq install -y emacs24 && apt-get clean
RUN apt-get -qq install -y erlang && apt-get clean
RUN apt-get -qq install -y f2c && apt-get clean
RUN apt-get -qq install -y fp-compiler && apt-get clean
RUN apt-get -qq install -y fsharp && apt-get clean
RUN apt-get -qq install -y g++ && apt-get clean
RUN apt-get -qq install -y gambas3-script && apt-get clean
RUN apt-get -qq install -y gap && apt-get clean
RUN apt-get -qq install -y gauche && apt-get clean
RUN apt-get -qq install -y gawk && apt-get clean
RUN apt-get -qq install -y gcc && apt-get clean
RUN apt-get -qq install -y gdc && apt-get clean
RUN apt-get -qq install -y genius && apt-get clean
RUN apt-get -qq install -y gforth && apt-get clean
RUN apt-get -qq install -y gfortran && apt-get clean
RUN apt-get -qq install -y ghc && apt-get clean
RUN apt-get -qq install -y ghostscript && apt-get clean
RUN apt-get -qq install -y gnat && apt-get clean
RUN apt-get -qq install -y gnu-smalltalk && apt-get clean
RUN apt-get -qq install -y gnuplot && apt-get clean
RUN apt-get -qq install -y gobjc && apt-get clean
RUN apt-get -qq install -y golang && apt-get clean
RUN apt-get -qq install -y gpt && apt-get clean
RUN apt-get -qq install -y gri && apt-get clean
RUN apt-get -qq install -y groff && apt-get clean
RUN apt-get -qq install -y groovy && apt-get clean
RUN apt-get -qq install -y haxe && apt-get clean
RUN apt-get -qq install -y icont && apt-get clean
RUN apt-get -qq install -y iconx && apt-get clean
RUN apt-get -qq install -y intercal && apt-get clean
RUN apt-get -qq install -y iverilog && apt-get clean
RUN apt-get -qq install -y jasmin-sable && apt-get clean
RUN apt-get -qq install -y jq && apt-get clean
RUN apt-get -qq install -y julia && apt-get clean
RUN apt-get -qq install -y libgd-dev && apt-get clean
RUN apt-get -qq install -y libpng12-dev && apt-get clean
RUN apt-get -qq install -y lisaac && apt-get clean
RUN apt-get -qq install -y llvm && apt-get clean
RUN apt-get -qq install -y lua5.3 && apt-get clean
RUN apt-get -qq install -y make && apt-get clean
RUN apt-get -qq install -y maxima && apt-get clean
RUN apt-get -qq install -y mlton && apt-get clean
RUN apt-get -qq install -y mono-devel && apt-get clean
RUN apt-get -qq install -y mono-mcs && apt-get clean
RUN apt-get -qq install -y mono-vbnc && apt-get clean
RUN apt-get -qq install -y nasm && apt-get clean
RUN apt-get -qq install -y neko && apt-get clean
RUN apt-get -qq install -y nickle && apt-get clean
RUN apt-get -qq install -y nim && apt-get clean
RUN apt-get -qq install -y ocaml && apt-get clean
RUN apt-get -qq install -y octave && apt-get clean
RUN apt-get -qq install -y open-cobol && apt-get clean
RUN apt-get -qq install -y openjdk-6-jdk && apt-get clean
RUN apt-get -qq install -y pari-gp && apt-get clean
RUN apt-get -qq install -y parrot && apt-get clean
RUN apt-get -qq install -y perl && apt-get clean
RUN apt-get -qq install -y php5-cli && apt-get clean
RUN apt-get -qq install -y pike8.0 && apt-get clean
RUN apt-get -qq install -y python && apt-get clean
RUN apt-get -qq install -y r-base && apt-get clean
RUN apt-get -qq install -y ratfor && apt-get clean
RUN apt-get -qq install -y regina-rexx && apt-get clean
RUN apt-get -qq install -y rhino && apt-get clean
RUN apt-get -qq install -y ruby2.1 && apt-get clean
RUN apt-get -qq install -y scala && apt-get clean
RUN apt-get -qq install -y scilab && apt-get clean
RUN apt-get -qq install -y slsh && apt-get clean
RUN apt-get -qq install -y spl-core && apt-get clean
RUN apt-get -qq install -y swi-prolog && apt-get clean
RUN apt-get -qq install -y tcl && apt-get clean
RUN apt-get -qq install -y ucblogo && apt-get clean
RUN apt-get -qq install -y valac && apt-get clean
RUN apt-get -qq install -y xsltproc && apt-get clean
RUN apt-get -qq install -y yorick && apt-get clean
RUN apt-get -qq install -y zoem && apt-get clean
RUN make -C vendor
CMD make check
