eval$s=%q(eval(%w(B=92.chr;g=32.chr;puts(eval(%q(N=10.chr;n=0;e=->s{Q[Q[s,B],?"].K(N,B+?n)};E=->s{'("'+e[s]+'")'};d=->s,t=?"{s.K(t){t+t}};def~f(s,n)s.K(/.{1,#{n*255}}/m){yield$S=E[$s=$&]}end;Q=->s,t=?${s.K(t){B+$&}};R=";return~0;";V=->
s,a,z{s.K(/(#{B*4})+/){a+"#{$&.size/2}"+z}};C=%w(System.Console~Write);$C=C*?.;$D="program~QR";$G="~contents~of"+$F="~the~mix!g~bowl";$L="public~static";rp=->s,r{v="";[r.!ject(s){|s,j|o={};m=n=0;s.size.times{|i|o[f=s[i,2]]||=0;c=o[f]+=
1;m<c&&(m=c;n=f)};v=n+v;s.K(n,(j%256).chr)},v]};"object~QR~extends~App{#{f(%((display~"#{e[%(Zf("1d;s/.//;s/1/~the~sum~of~a~son~and0/g;s/0/~twice/g;s/2/`x59ou~are~as~bad~as/g;s/3/~a~son`x21Speak~your~m!d`x21/g^n#The~Relay~of~Qu!e.^n#Aj
ax,~a~man.^n#Ford,~a~man.^n#Act~i:~Qu!e.^n#Scene~i:~Relay.^n#[Enter~Ajax~and~Ford]^n#Ajax:^n#");function[]=f(s);for~i=1:2:length(s),Zf("2%s3",part(dec2b!(hex2dec(part(s,i:i+1))),$:-1:2)),end;endfunction`n#{s,v=rp["Transcript~show:~'#{d
["Z"+E[%(fun~p~n=Z(Int.toSJ~n`x5e"~");p~0;p~0;p~130;List.tabulate(127,p);SJ.map(fn~c=>(p(3+ord~c);Z"-1~0~";c))#{E[%(puts~"#{Q[e[%(echo~'a::=`x7e#{Q[Q["let~s=#{E["!t~mX{Z#{d[E[%(module~QR;!itial~beg!~#{f("let~s=#{E[%(Module~QR:Sub~MX:Di
m~s,n,i,c~As~Object:n=Chr(10):For~Each~c~!"#{d["<?xml#{O="~version='1.0'"}?><?xml-#{I="stylesheet"}~type='text/xsl'href='QR.xslt'?><xsl:#{I+O}~xmlns:xsl='http://www.w3.org/1999/`x58SL/Transform'><xsl:output~method='text'/><#{U="xsl:tem
plate"}~match='/'><`x21[CDATA[#{%(sub~f(s$,n)Z(s$);:for~i=1to~n~Z("Y");:next:end~sub:f("#{V[e[%(H,format="#{y="";f("^H{-}{txt}{#{Q["echo~-E~$'#{Q[Q[E[%(with~Ada.Text_Io;procedure~qr~is~beg!~Ada.Text_Io.Put("#{d[%(!terp:library"afnix-si
o"`ntrans~O(n){trans~o(afnix:sio:OutputTerm)`no:H(Byte(+~128~n))}`ntrans~f(v~n){`nO(+(/~n~64)107)`nO(n:mod~64)`nO~v}`ntrans~D(n){if(<~n~4){f(+(*~6~n)9)48}{if(n:odd-p){D(-~n~3)`nf~27~48`nf~36~11}{D(/~n~2)`nf~21~48`nf~48~20}}}`ntrans~S"#
{e[%W[STRINGz:=~226+~153,a:=z+~166,b:=a+"2"+z+~160,c:=b+ "8"+z+~16  5,t:="#!clude<iostream>"+~(10)+"!t"+~(32)+"mX{puts#{d[E[%(class~QR{#$L~void~ma!(SJ[]v){System.out.Z(#{E["H('#{Q[e["implement~ma!0()=Z"+E["BEGIN{Z#{E[%(echo~'def!e~void
~f(n){"00g,";for(m=1;m<256;m*=2){"00g,4,:";if (n/m%2     )"4+      ";",";};    "4,:,"}"389**6+44*6+00p45*,";';Zf~"f(%d);`n"~`x60echo~'#{d[(s="#!clude<iostream>`n!t~mX{std::cout<<#{E[%(class~Program{#$L~void~MX{#$C("Qu!e~Relay~Coffee.^n
^nIngredients.^n");for(!t~i=9;i++<126;)#$C(   $"{       i                     }~g~caffe!e~{i}^n");#$C("^nMethod.^n");foreach(char~c~!#{E[%((doseq[s(lazy-cat["IDEN                TIFICATION~DIVISION.""PROGRAM-ID.~QR.""PROCEDURE~DIVISION
."'DISPLA`x59](map~#(str"~~~~^""(.replace    ~%                                          1"^"""^"^"")"^"&")(re-seq~#".{1,45}""#{e["(f=(n)->Array(n+1).jo                                  !~'Y');console.log('%s',#{V[E[%((H-l!e"#{e["ma!=p
utStr"+E["import~std.stdio;void~mX{H(`x                                                60#{%(method~MX{Z(@"#{d["[#{%(class~QR:Application{void~f(SJ                                            ~const~s,!t~n){for(Pr!t(s);n;n--)Pr!t("Y");}
void~MX{#{f("IO.puts"+E[%((pr!c~"#{e["                                                        `nma!(_)->`nio:fH#{d[E['Zfn("""'+d[?"+"echo~'#{Q[                                                    Q[%(~:~A~."#{g*9}"~;~:~B~A~."~WRITE(*,*)
'"~A~;~:~C~B~T`x59PE~."~'"~CR~;~:~D~S                                                             "~#$D"~C~S^"~Z~^"(&"~C~S^"~#{e[%(Z"#{e["s:                                                          =OutputTextUser();WriteAll(s,#{E[%(Zf
"#{e[d[f('set~Z"-";Z'+E[%(package~m                                                             a!;import"fmt";func~mX{fmt.Pr!t#{E[%(236:                                                                j;{119:i;{206i-:i;.48<{71+}{[i]^48
-*}if}%}:t;"algoritmo~QR;!"[195][     173]                                                           ++'cio~imprima("'"013141"t"/12131"                          t~6*"/1:191815                             1:??6271413/4=3626612/2/3532512
15/`x5a0`x5a0R"t"#{e[%(show~"z=n     ew~ja                                                               va.util.zip.G`x5aIPOutputStr                     eam(System.out);z.H('#{"ma!=                       putStr"+E["class~QR{#$L~functi
on~mX{neko.Lib.Z#{E[%(procedure      ~mX;                                                              i:=c:=0;s:=#{E[%(.class~pub                   lic~QR`n.super~#{$T="java/io/Pr!tStrea                    m"}`n.method~#$L~ma!([L#{S="
java/lang/S"}J;)V~;]`n.limit~st                      ack~2`ngetstatic~#{S}y                                stem/out~L#$T;`nldc~"#                 {e[%(class~QR{#$L~void~ma!(SJ[]v){SJ~c[]=new                   ~SJ[99999],y="",z=y,s="#{z
=t=(0..r=q=126).map{|n|[n,[]]};  a=""         ;b=->n{a<<(n%78+55)%84+42};(%(P={0                              :'[+[]]',m:'((+[]                )'+(C="['constructor']")+"+[])['11']"};for(R~!~B=(                 '`x21[]@`x21`x21[]@[][[]]
@'+(A="[]['fill']")+"@([]+[])['fo  ntcolor']([])@(+('11e20')+[])['split']([])@"+A+C+                            "('return~esc                ape')()("+A+')').split('@'))for(E~!~D=eval(G='('+B[R]+                 '+[])'))P[T=D[E]]=P[T]|
|G+"['"+E+"']";for(G='[',B=0;+     +B<36;)P[D=B.toSJ(36)]=B<10?(G+='+`x21+[]')+']':P[D                         ]||"(+('"+B+                "'))['to'+([]+[])"+C+"['name']]('36')";A+=C+"('console.log                (unescape(^"";for(E~!~
G=#{E[%(A=Z;A("echo~'k`x60"      );[(A("`x60`x60s"`x5e8*"i");for~j=6:-1:0;x=(Int(c)>>j)%2                         +1;A("`x               60"*"kki"[x:x+1])end)for~c~!~jo!(["Section`x48eader+name:=QR;                SectionPublic-ma!<-("
;["^"$(replace(replace(s,"     Y","YY"),"^"","Y^""))^".Z;"for~s=matchall(r".{1,99}",#{Q[E["                         cons               ole.log"+Q[E[%(@s=global[#{i=(s=%(`x48AI~1.2`nVISIBLE~"#{"x=sJ.K(               #{V[E["changequote(<
@,@>)`ndef!e(p,<@#{"all:      `n`t@echo~'#{d["l!el:99999;Z#{E["solve~satisfy;output~[#{E[%(.a                        ss   embly~t{}.method~#$L~void~MX{.entrypo!t~ldstr"#{e["m{{`x21:~x`nqr:~|-`n~:db`x60              #{e[s="$Z#{E[%(#!clu
de<stdio.h>`nmodule~QR      {}implementation{!t~mX__attribute__((C,spontaneous)){puts#{E["Zf#{E                     ["echo                 "+E["#import<stdio.h>#{N}!t~mX{puts#{E["Z_sJ"+E["s=toascii#{E["              Z#{E["$console:l!e[
#{"#$D(output);beg!~H      (#{f((p="eval";%($_="#{s,v=rp["$_='#{Q[%(<?php~$z=3+$w=strlen($s=#{Q[E                                                      ["!t~mX{H#{E["(#{?_*11})dup~=/s(|~~~~~.~~~|)def(#{Q               ["qr:-H('#{Q[e["!i
t{#{f(%(Z('cat("')`n      for~c~!"".jo!(["echo~'say~''%s'''^n"%l~for~l~!#{E[d[d[%(fn~mX{Zln`x21("{                                                           }",#{E["eval$s=%q(#$s)"]});}),?'],?']]}.split(              "^n")]):Z('r=fput(
char(%d))'%ord(c))`      nZ('end^n")')#),6){"Zf#{d[$S,?%]};"}}}"],?']}').",B]}){9~7{exch~dup~1~and~7                                                              9~mul~32~add~exch~2~idiv~3~1~roll~s~exch~              2~!dex~exch~put~1~
sub~dup~6~eq{1~sub}      if}repeat~s~=~pop~pop}forall~=~quit"]+R}}"]]})*3;echo"^x89PNG^r^n^x1a^n";$m=                                                                 "";$t="^xc0^0^xff";for($i=-1;++$i<128              *$z;$m.=$c--?($w-$
c||$i>$z)&&$i/$z<(      $c<$w?ord($s[(!t)($c/3)]):$c--%3+2)?$t[2].$t[$c%3%2].$t[$c%3]:"^0^0^0":"^0")$c=                                                                   $i%$z;foreach(array("I`x48DR".pack              ("NNCV",$w+2,128,
8,2),"IDAT".gzcomp      ress($m),"IEND")as$d)echo~pack("NA*N",strlen($d)-4,$d,crc32($d));).K(B,"`x7f"),?                                                                     ']}';s:g/^x7f/Y/;Z~$_",128..287              ];s="$_='#{Q[s,c=
/['Y]/]}';$n=32;$       s='#{Q[v,c]}';$s=`x7es{..}{$a=$&;$b=chr(--$n&255);`x7es/$b/$a/g;}eg;Z";(s+N*(-s.si                                                                      ze%6)).unpack("B*")[0].K(/.               {6}/){n=$&.to_i~2
;((n+14)/26*6+n+4       7).chr}}";s|.|$n=ord$&;substr~unpack(B8,chr$n-!t($n/32)*6-41),2|eg;eval~pack'B*',$_                                                                        ).scan(/[~,-:A-z]+|(.)/)              {p="s++#{$1?"chr~#
{$1.ord}+e":$&+?+       };"+p};p),1){"'#$s',"}}'')end.".K(/[:;()]/){?`x5e+$&}}]"]};quit"]};t=num2cell(b=11  -                                                                         ceil(s/13));for~n=1:9              m={};for~i=1:141f=
@(x,y,n)repmat(['       Ook'~char(x)~'~Ook'~char(y)~'~'],[1~abs(n)]);m(i)=[f(z=46,63,n)~f(q=z-(i<13)*13,     q,                    i-13)~f(33          ,z,1                             )~f(63,z,n)];end;t               (x)=m(diff([0~s(x=
b==n)])+13);end;Z       f('%%s',t{:})"]]+R}}"]]}`n"]};return~0;}~})]};"]}`x60`n~global~_start`n~_start:        m                   ov~edx,#{s.si     ze}`n~mov~e                          cx,m`n~mov~ebx,               1`n~mov~eax,4`n~!t~
128`n~mov~ebx,0`n~       mov~eax,1`n~!t~128`nx:~|`n~}}{{{qr}}}"]}"call~void~[mscorlib]#{C*"::"}(sJ)ret          }                    )]}];"]};quit(  );",?$].K(?'){          "'^''          "}}'"}@>)`np                "],?&,?&]},'&(%d+)&
',function(s)retur        n~sJ.rep('Y',tonumber(s))end);Z(x)".K(/[:"]/,":^0")}"`n`x4bT`x48`x58B`x59E             ~B                    `x59E)).size+1}x~i8]c"#{s.K(/[^     "`n`t]/){"^%       02`x58"%$                &.ord}}^00"declare~i
32@puts(i8*)def!e~i        32@mX{%1=call~i32@puts(i8*getelementptr([#{i}x~i8],[#{i}x~i8]*@s,i32~0,i             32~0                    ))ret~i32~0})],?#]]]})];");"],"^   n")];[for~i=0:2:     4;x=((                Int(c)%83-10)>>i)%4+1
;A("ski`x60"[x:x])en        d~for~c~!"AG-`x48-`x48Fy.IlD==;=jdlAy=;=jldltldltl{lAulAy=jtlldlAyFy=             ?=jdlAyG                    FyFyG2AFy>zlAFFBCjldGyGFy>GFy.AG y=G==n`x48==nlldC=j   @=j                 tlldltldlAut11"];A("'"
))]})A+="'+`x21[]+'"         +G.charCodeAt(E).toSJ(16);for(A+="^".replace(/'+`x21[]+'/g,^"%^"))              )')()",R=0                     ;R<9;R++)A=A.replace(/'.*?'/g,function(B){T=[];for(E =                  1;B[E+1];)T.push(P[B[E+
+]]);return~T.jo!('+'         )});console.log('"'+A+'"'))).bytes{|n|r,z=z[n]||(b[r/78];b[r];q              <6083&&z[n]=[q                      +=1,[]];t[n])};b[r/78];b[r]}";!t~i=0,n=0,q=0;for(                   ;++n<126;)c[n]=""+(char)
n;for(;i<#{a.size};){q          =q*78+(s.charAt(i)-13)%84;if(i++%2>0){y=q<n?c[q]:y;c[n++]=z+             y.charAt(0);System                      .out.Z(z=c[q]);q=0;}}}})]}"`n!vokevirtual~#$T                   /Zln(L#{S}J;)V`nreturn`n.e
nd~method)+N]};H("DO,1<-          #"||*s);s?while~t:=ord(move(1))do{i+:=1;u:=-i;every~0to              ~7do{u:=u*2+t%2;t/:=2                        };H("PLEASE")^(i%4/3);H("DO,1SUB#"||i||                     "<-#"||((c-u)%256));c:=u;};
H("PLEASEREADOUT,1^nPLEAS           EGIVEUP");end)]};}}"].tr(?"+B,"`x21`x7e")}'.tr('`x7               e`x21','YY^u0022')as~byt                          e[]);z.close()"`n)]}"{"W""w"@j~                       1+:j^-~118%1+*}%"/35512416612
G61913@921/17A331513"t'");f            im')]};})],61){"Zn#$S`n"},?%]]}"`nquit)]});Cl                oseStream(s);QUIT;"]}")]}"~D                              UP~A~."~DO~10~I=1,                            "~.~CR~S"~&A,&"~C~."~10~~~~~~CO
NTINUE"~CR~S^"~&A)^",&"~C~0~D             O~B~."~&char("~COUNT~.~."~),&'"~CR~LOOP                ~S^"~&^"^""~C~S"~end~#$D"~C~A~."~S                                                                       TOP"~CR~A~."~END"~CR~B`x59E~;~D~)
,B],?`x21].K(?',%('"'"'))}'".K(                ?"){'"34,"'}.K(N){'"10,"'}+?",                  ?%]+'~""")'],?`x7e]}."]}"))],15){"f(#{                                                                   V[$S[1..-2],'",',');f("']},0);"}}}}
)}]pq"]}");})}`x60);}"]]}"))].K(?                     `x60,"Yx60"),'#                       {f(',')}']})"]}"))["~~~~^"~^".""STOP~RUN."])                                                             ](Zln(str"message(STATUS~^"~~~~~"(.rep
lace(.replace(str~s)"Y""YY")"^"""Y^"                                                     ")"^")")))).reverse]})#$C($"Put~caffe!e~{(!t)c}~!t                                                       o#$F.^n");#$C("Liquify#$G.^nPour#$G~!to~t
he~bak!g~dish.^n^nServes~1.^n");}})]};}                                               /****//****/";t={};b="";L="";n=i=0;D=->n{L<<(n+62)%92+35;                                               D};s.bytes{|c|n>0?n-=1:(t[c]=(t[c]||[]).rejec
t{|j|j<i-3560};x=[];t[c].map{|j|k=(0..90).f!                                      d{|k|not~s[i+1+k]==s[j+k]}||91;k>4&&x<<[k,j]};x=x.max)?(n,j=x;x=b                                       .size;(u=[x,3999].m!;D[u%87][u/87];L<<b[0,u];b[0,
u]="";x-=u)while~x>0;x=4001+i-j;D[x%87][x/87][n-5]                         ):b<<c;t[c]+=[i+=1]};"#!clude<stdio.h>`nchar*p=#{E[L]},s[999999],*q=s;!t~mX{!t~                         n,m;for(;*p;){n=(*p-5)%92+(p[1]-5)%92*87;p+=2;if(n>3999)
for(m=(*p++-5)%92+6;m--;q++)*q=q[4000-n];else~for(;n--;)*q++=*p++;}puts(s)#{R}}"),B].K(?',%('"'"'))}'|od~-An~-tuC`x60;Zf~'"4,:,';Zf~'%sY8*+Y88**+,'~`x60echo~kaARERE`x58/I0ALn3n5ef6l/Pz8+fnz58/BOf5/7/hE`x58/O`x5azM5mC`x58/Oczm`x5azBPn5+
`x58/OczMznBL/nM5m`x5azBPu++fPPOc5zngnnO`x5azO`x5agnBMGAW7A==|base64~-d|od~-An~-toC`x60;Zf~"@^"`nquit")]}}"]],?']}');".K(B,?`x5e)]}.replace("`x5e","Y"));}})]]};}";FORiTO`~UPBtDO`~INTn:=ABSt[i];Z(~(50+n%64)+c+~(50+n%8MOD8)+c+~(50+nMOD8)
+b+"`x4a"+a)OD]*"REPR"]}"`ntrans~c~0`ndo{D(Integer(S:get~c))`nf~35~39}(<(c:++)(S:length))`nf~24~149)].K(N,'"&Character'+?'+'Val(10)&"')}");end;)]+"`nsys.exit~0",B],?']}'",/[^{}]/]}}",35){y<<",`n"+$S;"%s"}}")+y],'",','):f("']}",0))}]]><
/#{U}></xsl:#{I}>"].K~N,'"&~VbLf~&"'}":s="~~~":For~i=0To~7:s~&=Chr(32-(Asc(c)>>7-i~And~1)*23):Next:#$C(s~&n~&Chr(9)&n~&"~~"):Next:#$C(n~&n~&n):End~Sub:End~Module)]}`nput=s`nZ`nqa`x21",3){%($H("%s",#$S);)+N}}end~endmodule)],?%]+R}}"]},i
=0,t='k';while(s[i])t='^x60.'+s[i++]+t;console.log(t)",B],?`x21].K(?',%('"'"'))}'"^n::=^na")],/[`[`]$]/]}")]};Z"0~0~-1";)],?']}';cr",127..255];f(%(variable~s=`x60#{s.K(/.{1,234}/){$&.K("`x60",%(`x60+"`x60"+`x60))+"`x60+`n`x60"}}`x60,i;
for(i=0;i<129;i++)s=strreplace(s,pack("C",255-i),substrbytes(`x60#{v[0,99]}`x60+`n`x60#{v[99..-1]}`x60,i*2+1,2));Zf("%s",s)),7){"f('%s')`n"%$s.unpack("`x48*")}}Zf("^n#[Exeunt]");quit)]}")),196){%(Z#$S;)}}}").gsub(/[!HJKXYZ^`~]/){[B*2,:
write,B,:tring,:gsub,"ain()",B*4,:print,g,:in][$&.ord%47%12]})))*"")#_buffer_for_future_bug_fixes_#_buffer_for_future_bug_fixes_#_buffer_for_future_bug_fixes_#_buffer_for_future_bug_fixes_#_buffer_for_future_bug_fixes_#_buffer_for_futu
##############################################################################  Quine Relay -- Copyright (c) 2013, 2014 Yusuke Endoh (@mametter), @hirekoke  #############################################################################)
