require "rake/clean"

CLEAN.include("../QR.*")
CLEAN.include("../qr.*")
CLEAN.include("../QR$*")
CLEAN.include("../QR")
CLEAN.include("../qr")
CLEAN.include("../QR2.rb")
CLEAN.include("../README.md")
CLEAN.include("../langs.png")
CLEAN.include("../Makefile")

LIBS = %w(code-gen.rb code-gen-pool.rb lazyk-boot.dat blc-boot.dat grass-boot.dat)

file "lazyk-boot.dat" => "lazyk-boot.dat.gen.rb" do
  ruby "lazyk-boot.dat.gen.rb"
end

file "blc-boot.dat" => "blc-boot.dat.gen.rb" do
  ruby "blc-boot.dat.gen.rb"
end

file "grass-boot.dat" => "grass-boot.dat.gen.rb" do
  ruby "grass-boot.dat.gen.rb"
end

file "../QR.rb" => ["QR.rb.gen.rb", *LIBS, "uroboros.txt"] do
  ruby "QR.rb.gen.rb"
end

file "../README.md" => ["README.md.gen.rb", *LIBS] do
  ruby "README.md.gen.rb"
end

file "../langs.png" => ["langs.png.gen.rb", "uroboros.svg", *LIBS] do
  ruby "langs.png.gen.rb"
end

file "../thumbnail.png" => ["thumbnail.png.gen.rb", "../QR.rb"] do
  ruby "thumbnail.png.gen.rb"
end

file "../Makefile" => ["Makefile.gen.rb", *LIBS] do
  ruby "Makefile.gen.rb"
end

file "../.travis.yml" => ["dot.travis.yml.gen.rb", *LIBS] do
  ruby "dot.travis.yml.gen.rb"
end

file "../Dockerfile" => ["Dockerfile.gen.rb", *LIBS] do
  ruby "Dockerfile.gen.rb"
end

task :test do
  ruby "test.rb"
end

task :default => %w(
  ../QR.rb
  ../README.md
  ../langs.png
  ../thumbnail.png
  ../Makefile
  ../.travis.yml
  ../Dockerfile
)

task "../SHA1SUMS" => ["SHA1SUMS.gen.rb", *LIBS] do
  ruby "SHA1SUMS.gen.rb"
end

task :run => :default do
  sh "make -C .."
end

task :gen => [:run, "../SHA1SUMS"]
