require "rake/clean"
require_relative "code-gen"

CLEAN.include("../QR.*")
CLEAN.include("../qr.*")
CLEAN.include("../QR$*")
CLEAN.include("../QR")
CLEAN.include("../qr")
CLEAN.include("../QR2.rb")
CLEAN.include("../README.md")
CLEAN.include("../langs.png")
CLEAN.include("../Makefile")

file "../QR.rb" => ["QR.rb.gen.rb", "code-gen.rb", "uroboros.txt"] do |t|
  ruby "QR.rb.gen.rb"
end

file "../README.md" => ["README.md.gen.rb", "code-gen.rb"] do |t|
  ruby "README.md.gen.rb"
end

file "../langs.png" => ["langs.png.gen.rb", "uroboros.svg", "code-gen.rb"] do |t|
  ruby "langs.png.gen.rb"
end

file "../thumbnail.png" => ["thumbnail.png.gen.rb", "../QR.rb"] do |t|
  ruby "thumbnail.png.gen.rb"
end

file "../Makefile" => ["Makefile.gen.rb", "code-gen.rb"] do |t|
  ruby "Makefile.gen.rb"
end

file "../.travis.yml" => ["dot.travis.yml.gen.rb", "code-gen.rb"] do |t|
  ruby "dot.travis.yml.gen.rb"
end

file "../Dockerfile" => ["Dockerfile.gen.rb", "code-gen.rb"] do |t|
  ruby "Dockerfile.gen.rb"
end

task :test do
  ruby "test.rb"
end

task :default => %w(
  ../QR.rb
  ../README.md
  ../langs.png
  ../thumbnail.png
  ../Makefile
  ../.travis.yml
  ../Dockerfile
)

task "../SHA1SUMS" => ["code-gen.rb"] do |t|
  chdir ".." do
    sh "sha1sum -b #{ RunSteps.map {|s| s.src }.join(" ") } > SHA1SUMS"
  end
end
