require "rake/clean"

CLEAN.include("../QR.*")
CLEAN.include("../qr.*")
CLEAN.include("../QR$*")
CLEAN.include("../QR")
CLEAN.include("../qr")
CLEAN.include("../QR2.rb")
CLEAN.include("../README.md")
CLEAN.include("../langs.png")
CLEAN.include("../Makefile")
CLEAN.include("../unlambda.rb")
CLEAN.include("../whitespace.rb")

file "../QR.rb" => ["QR.rb.gen.rb", "code-gen.rb", "uroboros.txt"] do |t|
  ruby "QR.rb.gen.rb"
end

file "../README.md" => ["README.md.gen.rb", "code-gen.rb"] do |t|
  ruby "README.md.gen.rb"
end

file "../langs.png" => ["langs.png.gen.rb", "uroboros.svg", "code-gen.rb"] do |t|
  ruby "langs.png.gen.rb"
end

file "../Makefile" => ["Makefile.gen.rb", "code-gen.rb"] do |t|
  ruby "Makefile.gen.rb"
end

file "../unlambda.rb" => ["unlambda.rb"] do |t|
  cp "unlambda.rb", t.name
end

file "../whitespace.rb" => ["whitespace.rb"] do |t|
  cp "whitespace.rb", t.name
end

task :test do
  ruby "test.rb"
end

task :default => %w(
  ../QR.rb
  ../README.md
  ../langs.png
  ../Makefile
  ../unlambda.rb
  ../whitespace.rb
)
